version: '3'
services:
  lldb-playground:
    volumes:
      - lldb-playground-bash-history:/commandhistory

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
volumes:
  lldb-playground-bash-history: